"""
AI Development Kit

Continue Builder
"""

from __future__ import annotations

from pathlib import Path

from aidk.core.filesystem import FileSystem
from aidk.core.template_engine import TemplateEngine


class ContinueBuilder:

    def __init__(self, root: str | Path):

        self.root = Path(root)

        self.continue_dir = self.root / ".continue"

    def create_structure(self) -> None:

        folders = [
            "agents",
            "rules",
            "prompts",
            "mcpServers",
            "templates",
        ]

        for folder in folders:

            FileSystem.mkdir(
                self.continue_dir / folder
            )

    def create_config(self) -> None:

        template = """
name: {{ name }}
version: 1.0.0
schema: v1

models: []
rules: []
prompts: []
"""

        content = TemplateEngine.render(
            template,
            {
                "name": "AI Development Kit",
            },
        )

        FileSystem.write(
            self.continue_dir / "config.yaml",
            content,
        )

    def create_readme(self) -> None:

        text = """# Continue

Generated by AI Development Kit.
"""

        FileSystem.write(
            self.continue_dir / "README.md",
            text,
        )

    def build(self) -> None:

        self.create_structure()

        self.create_config()

        self.create_readme()
